// Midnight Madness, Inc.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace GoliathGameplayTags
{
	/** Player Input Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_Rage);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Light);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Heavy);
	
	/** Player Ability Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Rage);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Light);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Heavy);
	
	/** Player Cooldown Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Light);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Heavy);
	
	/** Player Weapon Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	
	/** Player Event Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ActivateRage);
	
	/** Player Status Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Activating);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Active);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Full);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_None);
	
	/** Player SetByCaller Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);
	
	/** Enemy Ability Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies);
	
	/** Enemy Weapon Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	
	/** Enemy Event Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SummonEnemies);
	
	/** Enemy Status Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Unblockable);
	
	/** Shared Ability Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	/** Shared Event Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);
	
	/** Shared SetByCaller Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	
	/** Shared Status Tags **/
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	GOLIATH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible);
}
